import React from 'react'

export const metadata = {
    title: 'Home page',
    description: 'Generated by create next app',
}

export default async function HomeLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <main className='min-h-[90vh]'>
            {children}
        </main>
    )
}
