import React from 'react'

export const metadata = {
    title: 'Boutique page',
    description: 'Generated by create next app',
}

export default async function ProductLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <main className='min-h-[90vh] px-4'>
            {children}
        </main>
    )
}
